# Generated by Django 6.0.7 on 2026-07-30 06:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday'), ('flexible', 'Flexible')], default='flexible', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_rest_day', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.workoutprogram')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProgramExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('target_sets', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('target_reps_min', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('target_reps_max', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('target_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('rest_seconds', models.PositiveIntegerField(default=90)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='program_uses', to='exercises.exercise')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.programday')),
            ],
            options={
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('program_day', 'order'), name='unique_exercise_order_per_day'), models.UniqueConstraint(fields=('program_day', 'exercise'), name='unique_exercise_per_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='workoutprogram',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_program_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='workoutprogram',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='one_active_program_per_user'),
        ),
        migrations.AddConstraint(
            model_name='programday',
            constraint=models.UniqueConstraint(fields=('program', 'order'), name='unique_day_order_per_program'),
        ),
    ]
