# Generated by Django 6.0.7 on 2026-07-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutset',
            name='is_extra',
            field=models.BooleanField(default=False),
        ),
    ]
