# Generated by Django 6.0.7 on 2026-07-30 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.equipment')),
                ('primary_muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_exercises', to='exercises.musclegroup')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_exercises', to='exercises.musclegroup')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('created_by__isnull', True), ('is_custom', False)), models.Q(('created_by__isnull', False), ('is_custom', True)), _connector='OR'), name='exercise_custom_owner_consistency'), models.UniqueConstraint(condition=models.Q(('is_custom', False)), fields=('name',), name='unique_system_exercise_name'), models.UniqueConstraint(condition=models.Q(('is_custom', True)), fields=('created_by', 'name'), name='unique_custom_exercise_name_per_user')],
            },
        ),
    ]
